name: Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-yrs_uniffi-macos:
    runs-on: macos-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: prepare x86_64
        run: rustup target add aarch64-apple-darwin

      - name: prepare aarch64
        run: rustup target add x86_64-apple-darwin

      - name: build x86_64
        run: cargo build --release -p yrs_uniffi --target x86_64-apple-darwin

      - name: build aarch64
        run: cargo build --release -p yrs_uniffi --target aarch64-apple-darwin

      - name: Upload lib x86_64
        uses: actions/upload-artifact@v4
        with:
          name: uniffi-darwin-x86_64
          path: target/x86_64-apple-darwin/release/libyrs_uniffi.dylib

      - name: Upload lib aarch64
        uses: actions/upload-artifact@v4
        with:
          name: uniffi-darwin-aarch64
          path: target/aarch64-apple-darwin/release/libyrs_uniffi.dylib


  build-yrs_uniffi-linux:
    runs-on: ubuntu-latest
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build
        run: cargo build --release -p yrs_uniffi

      - name: export kotlin uniffi
        run: cargo run --features=uniffi/cli --bin uniffi-bindgen generate --language kotlin --out-dir yrs_kt/src/main/kotlin --library target/release/libyrs_uniffi.so

      - name: Upload lib
        uses: actions/upload-artifact@v4
        with:
          name: uniffi-linux
          path: target/release/libyrs_uniffi.so

      - name: Upload kotlin uniffi
        uses: actions/upload-artifact@v4
        with:
          name: kt-uniffi
          path: yrs_kt/src/main/kotlin/com/planerist/ykt/yrs_uniffi.kt

  build-yrs_kt:
    runs-on: ubuntu-latest
    needs: [build-yrs_uniffi-linux, build-yrs_uniffi-macos]
    steps:
      - name: checkout sources
        uses: actions/checkout@v2

      - name: install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/download-artifact@v4
        with:
          name: kt-uniffi
          path: yrs_kt/src/main/kotlin/com/planerist/ykt/yrs_uniffi.kt

      - uses: actions/download-artifact@v4
        with:
          name: uniffi-linux
          path: yrs_kt/src/main/resources/linux-x86-64/

      - uses: actions/download-artifact@v4
        with:
          name:  uniffi-darwin-x86_64
          path: yrs_kt/src/main/resources/darwin-x86-64/

      - uses: actions/download-artifact@v4
        with:
          name: uniffi-darwin-aarch64
          path: yrs_kt/src/main/resources/darwin-aarch64/

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build y_kt
        run: ./gradlew build test jar kotlinSourcesJar

      - name: Upload jar
        uses: actions/upload-artifact@v4
        with:
          name: ykt
          path: yrs_kt/build/libs